deviceName = emulator-5554
platformName = Android
automationName = uiautomator2
myAppPackage = com.alfabank.qapp
myAppActivity = com.alfabank.qapp.presentation.MainActivity

appiumServer = http://127.0.0.1:4723